# Generated by Django 5.1 on 2024-08-13 11:55

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemessage',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CN'),
        ),
    ]
